#include "CListeMatrice.h"




void CListeMatrice::LISajouter(CMatrice MATmat)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:00000000000009A1 begin
{
}
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:00000000000009A1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void CListeMatrice::LISsupprimer(Integer uiPosition)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:00000000000009A4 begin
{
}
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:00000000000009A4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void CListeMatrice::LISviderListe()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:00000000000009A7 begin
{
}
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:00000000000009A7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void CListeMatrice::LISajouter(void  sChemin)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:00000000000009A9 begin
{
}
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:00000000000009A9 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
