#include "CMatrice.h"


<<<<<<< HEAD
/*CMatrice CMatrice::operator+(CMatrice MATmat)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:0000000000000989 begin
=======


CMatrice CMatrice::operator+(CMatrice MATmat)
>>>>>>> 583d311b88a6062c88226f214b8962dc0e3f16a4
{
}


CMatrice CMatrice::operator*(double  dVal, CMatrice MATmat)
{
}

CMatrice CMatrice::operator-(CMatrice MATmat)
{
}

CMatrice CMatrice::operator/(CMatrice MATmat)
{
}

CMatrice CMatrice::operator*(CMatrice MATmat)
{
}

CMatrice CMatrice::operator/(double  dVal)
{
}

void CMatrice::MATafficherMatrice()
{
}

CMatrice CMatrice::MATtransposee()
{
}

CMatrice CMatrice::operator*(double  dVal)
{
<<<<<<< HEAD
}*/
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:000000000000098C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
=======
}
>>>>>>> 583d311b88a6062c88226f214b8962dc0e3f16a4
