#include "CMatrice.h"


/*CMatrice CMatrice::operator+(CMatrice MATmat)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:0000000000000989 begin
{
}
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:0000000000000989 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

CMatrice CMatrice::operator*(double  dVal, CMatrice MATmat)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:000000000000098F begin
{
}
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:000000000000098F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

CMatrice CMatrice::operator-(CMatrice MATmat)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:0000000000000993 begin
{
}
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:0000000000000993 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

CMatrice CMatrice::operator/(CMatrice MATmat)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:0000000000000996 begin
{
}
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:0000000000000996 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

CMatrice CMatrice::operator*(CMatrice MATmat)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:0000000000000999 begin
{
}
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:0000000000000999 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

CMatrice CMatrice::operator/(double  dVal)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:000000000000099C begin
{
}
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:000000000000099C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void CMatrice::MATafficherMatrice()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:000000000000099F begin
{
}
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:000000000000099F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

CMatrice CMatrice::MATtransposee()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:00000000000009AC begin
{
}
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:00000000000009AC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

CMatrice CMatrice::operator*(double  dVal)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:000000000000098C begin
{
}*/
// section 127-0-1-1--7fc8ad4c:1626b480a96:-8000:000000000000098C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
